/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGUI;

/**
 *
 * @author AluDAM
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        etiTitulo = new javax.swing.JLabel();
        etiNickEntrar = new javax.swing.JLabel();
        etiContraseñaEntrar = new javax.swing.JLabel();
        botonEntrar = new javax.swing.JButton();
        textNickEntrar = new javax.swing.JTextField();
        textContraseñaEntrar = new javax.swing.JTextField();
        botonOlvidadoContraseña = new javax.swing.JButton();
        lineaSeparador = new javax.swing.JSeparator();
        etiImagen = new javax.swing.JLabel();
        etiNickRegistrarse = new javax.swing.JLabel();
        etiEmailRegistrarse = new javax.swing.JLabel();
        etiTelefonoRegistrarse = new javax.swing.JLabel();
        etiContraseñaRegistrarse = new javax.swing.JLabel();
        etiRepiteContraseñaRegistrarse = new javax.swing.JLabel();
        textNickRegistrarse = new javax.swing.JTextField();
        textEmailRegistrarse = new javax.swing.JTextField();
        textTelefonoRegistrarse = new javax.swing.JTextField();
        textContraseñaRegistrarse = new javax.swing.JTextField();
        textRepetirContraseñaRegistrarse = new javax.swing.JTextField();
        confirmacionRecibirInformacion = new javax.swing.JCheckBox();
        botonRegistrarse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("La compra en casa");
        setBackground(new java.awt.Color(255, 255, 255));

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setForeground(new java.awt.Color(255, 255, 255));

        etiTitulo.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        etiTitulo.setForeground(new java.awt.Color(0, 102, 255));
        etiTitulo.setText("Mi Web");

        etiNickEntrar.setForeground(new java.awt.Color(0, 0, 0));
        etiNickEntrar.setText("Nick");

        etiContraseñaEntrar.setForeground(new java.awt.Color(0, 0, 0));
        etiContraseñaEntrar.setText("Contraseña");

        botonEntrar.setBackground(new java.awt.Color(102, 102, 255));
        botonEntrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonEntrar.setText("ENTRAR");

        textNickEntrar.setBackground(new java.awt.Color(229, 229, 255));
        textNickEntrar.setForeground(new java.awt.Color(0, 0, 0));
        textNickEntrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        textContraseñaEntrar.setBackground(new java.awt.Color(229, 229, 255));
        textContraseñaEntrar.setForeground(new java.awt.Color(0, 0, 0));
        textContraseñaEntrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        botonOlvidadoContraseña.setBackground(new java.awt.Color(102, 102, 255));
        botonOlvidadoContraseña.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonOlvidadoContraseña.setText("¿Has olvidado la contraseña?");

        lineaSeparador.setForeground(new java.awt.Color(0, 51, 255));

        etiImagen.setForeground(new java.awt.Color(0, 0, 0));
        etiImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/825575.png"))); // NOI18N

        etiNickRegistrarse.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        etiNickRegistrarse.setForeground(new java.awt.Color(0, 0, 0));
        etiNickRegistrarse.setText("Nick");

        etiEmailRegistrarse.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        etiEmailRegistrarse.setForeground(new java.awt.Color(0, 0, 0));
        etiEmailRegistrarse.setText("Correo electrónico");

        etiTelefonoRegistrarse.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        etiTelefonoRegistrarse.setForeground(new java.awt.Color(0, 0, 0));
        etiTelefonoRegistrarse.setText("Teléfono");

        etiContraseñaRegistrarse.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        etiContraseñaRegistrarse.setForeground(new java.awt.Color(0, 0, 0));
        etiContraseñaRegistrarse.setText("Contraseña");

        etiRepiteContraseñaRegistrarse.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        etiRepiteContraseñaRegistrarse.setForeground(new java.awt.Color(0, 0, 0));
        etiRepiteContraseñaRegistrarse.setText("Repetir Contraseña");

        textNickRegistrarse.setBackground(new java.awt.Color(229, 229, 255));
        textNickRegistrarse.setForeground(new java.awt.Color(0, 0, 0));
        textNickRegistrarse.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        textEmailRegistrarse.setBackground(new java.awt.Color(229, 229, 255));
        textEmailRegistrarse.setForeground(new java.awt.Color(0, 0, 0));
        textEmailRegistrarse.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        textTelefonoRegistrarse.setBackground(new java.awt.Color(229, 229, 255));
        textTelefonoRegistrarse.setForeground(new java.awt.Color(0, 0, 0));
        textTelefonoRegistrarse.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        textContraseñaRegistrarse.setBackground(new java.awt.Color(229, 229, 255));
        textContraseñaRegistrarse.setForeground(new java.awt.Color(0, 0, 0));
        textContraseñaRegistrarse.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        textRepetirContraseñaRegistrarse.setBackground(new java.awt.Color(229, 229, 255));
        textRepetirContraseñaRegistrarse.setForeground(new java.awt.Color(0, 0, 0));
        textRepetirContraseñaRegistrarse.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        confirmacionRecibirInformacion.setForeground(new java.awt.Color(0, 0, 0));
        confirmacionRecibirInformacion.setText("Deseo recibir información cada diez minutos");

        botonRegistrarse.setBackground(new java.awt.Color(102, 102, 255));
        botonRegistrarse.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonRegistrarse.setText("REGISTRARSE");

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lineaSeparador)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(etiTitulo)
                                .addGap(76, 76, 76)
                                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(fondoLayout.createSequentialGroup()
                                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(etiNickEntrar)
                                            .addComponent(textNickEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(31, 31, 31)
                                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(etiContraseñaEntrar)
                                            .addComponent(textContraseñaEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(botonOlvidadoContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(confirmacionRecibirInformacion)
                                .addGap(18, 18, 18))
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(etiImagen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etiEmailRegistrarse, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(etiNickRegistrarse, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(etiTelefonoRegistrarse, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(etiContraseñaRegistrarse, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(etiRepiteContraseñaRegistrarse, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(27, 27, 27)))
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textEmailRegistrarse, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textContraseñaRegistrarse)
                            .addComponent(textTelefonoRegistrarse)
                            .addComponent(textNickRegistrarse)
                            .addComponent(textRepetirContraseñaRegistrarse, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonRegistrarse, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))))
                .addGap(25, 25, 25))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(etiNickEntrar)
                                    .addComponent(etiContraseñaEntrar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textContraseñaEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textNickEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonOlvidadoContraseña))
                            .addComponent(botonEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(etiTitulo)
                        .addGap(16, 16, 16)))
                .addComponent(lineaSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiNickRegistrarse)
                            .addComponent(textNickRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiEmailRegistrarse)
                            .addComponent(textEmailRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiTelefonoRegistrarse)
                            .addComponent(textTelefonoRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textContraseñaRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiContraseñaRegistrarse))
                        .addGap(18, 18, 18)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textRepetirContraseñaRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiRepiteContraseñaRegistrarse)))
                    .addComponent(etiImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(botonRegistrarse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(30, 30, 30))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(confirmacionRecibirInformacion)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEntrar;
    private javax.swing.JButton botonOlvidadoContraseña;
    private javax.swing.JButton botonRegistrarse;
    private javax.swing.JCheckBox confirmacionRecibirInformacion;
    private javax.swing.JLabel etiContraseñaEntrar;
    private javax.swing.JLabel etiContraseñaRegistrarse;
    private javax.swing.JLabel etiEmailRegistrarse;
    private javax.swing.JLabel etiImagen;
    private javax.swing.JLabel etiNickEntrar;
    private javax.swing.JLabel etiNickRegistrarse;
    private javax.swing.JLabel etiRepiteContraseñaRegistrarse;
    private javax.swing.JLabel etiTelefonoRegistrarse;
    private javax.swing.JLabel etiTitulo;
    private javax.swing.JPanel fondo;
    private javax.swing.JSeparator lineaSeparador;
    private javax.swing.JTextField textContraseñaEntrar;
    private javax.swing.JTextField textContraseñaRegistrarse;
    private javax.swing.JTextField textEmailRegistrarse;
    private javax.swing.JTextField textNickEntrar;
    private javax.swing.JTextField textNickRegistrarse;
    private javax.swing.JTextField textRepetirContraseñaRegistrarse;
    private javax.swing.JTextField textTelefonoRegistrarse;
    // End of variables declaration//GEN-END:variables
}
